repos:
  - repo: local
    hooks:
      - id: make-lint
        name: make lint
        entry: make lint
        language: system
        types: [proto]
        files: ^proto/.*\.proto$
        pass_filenames: false
      - id: make-breaking
        name: make breaking
        entry: make breaking
        language: system
        types: [proto]
        files: ^proto/.*\.proto$
        pass_filenames: false
      - id: make-generate
        name: make generate
        entry: make generate
        language: system
        types: [proto]
        files: ^proto/.*\.proto$
        pass_filenames: false
